### ISSUE TITLE
$CUDAHOME or $CUDA_HOME

### ISSUE THREAD

**Issue by skyer9** [kakao/buffalo#10]
i think `$CUDA_HOME` is used more frequently than `$CUDAHOME`.

**Comment by ummae** [comment]
It would be better to check both values.

**Comment by ummae** [comment]
We update the locations where finding CUDA libs as CUDA_PATH, CUDAHOME, CUDA_HOME.

https://github.com/kakao/buffalo/blob/dev/cuda_setup.py#L34
