### ISSUE TITLE
pip install n2시 오류

### ISSUE THREAD

**Issue by joseungwoo** [kakao/buffalo#19]
Collecting n2
  Using cached https://files.pythonhosted.org/packages/ac/e7/1758cd0973aa2b1a46ad3556bf37c7a625eec7f603f3389a4908d0f70a14/n2-0.1.4.tar.gz
Requirement already satisfied: cython in /Users/seungwoo/PycharmProjects/flaskrestful/venv/lib/python3.7/site-packages (from n2) (0.29.14)
Building wheels for collected packages: n2
  Building wheel for n2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/seungwoo/PycharmProjects/flaskrestful/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-install-mq_r5hg2/n2/setup.py'"'"'; __file__='"'"'/private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-install-mq_r5hg2/n2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-wheel-0ob5uuf7 --python-tag cp37
       cwd: /private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-install-mq_r5hg2/n2/
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'n2' extension
  creating build
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/bindings
  creating build/temp.macosx-10.9-x86_64-3.7/bindings/python
  creating build/temp.macosx-10.9-x86_64-3.7/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I./include/ -I./third_party/spdlog/include/ -I/Users/seungwoo/PycharmProjects/flaskrestful/venv/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c ./bindings/python/n2.cpp -o build/temp.macosx-10.9-x86_64-3.7/./bindings/python/n2.o -std=c++11 -O3 -fPIC -march=native -fopenmp
  clang: error: unsupported option '-fopenmp'
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for n2
  Running setup.py clean for n2
Failed to build n2
Installing collected packages: n2
    Running setup.py install for n2 ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/seungwoo/PycharmProjects/flaskrestful/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-install-mq_r5hg2/n2/setup.py'"'"'; __file__='"'"'/private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-install-mq_r5hg2/n2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-record-ui4nsmpl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/seungwoo/PycharmProjects/flaskrestful/venv/include/site/python3.7/n2
         cwd: /private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-install-mq_r5hg2/n2/
    Complete output (12 lines):
    running install
    running build
    running build_ext
    building 'n2' extension
    creating build
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/bindings
    creating build/temp.macosx-10.9-x86_64-3.7/bindings/python
    creating build/temp.macosx-10.9-x86_64-3.7/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I./include/ -I./third_party/spdlog/include/ -I/Users/seungwoo/PycharmProjects/flaskrestful/venv/include -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c ./bindings/python/n2.cpp -o build/temp.macosx-10.9-x86_64-3.7/./bindings/python/n2.o -std=c++11 -O3 -fPIC -march=native -fopenmp
    clang: error: unsupported option '-fopenmp'
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/seungwoo/PycharmProjects/flaskrestful/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-install-mq_r5hg2/n2/setup.py'"'"'; __file__='"'"'/private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-install-mq_r5hg2/n2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/pf/f_mv79jj0xn20ymmnjr923yr0000gn/T/pip-record-ui4nsmpl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/seungwoo/PycharmProjects/flaskrestful/venv/include/site/python3.7/n2 Check the logs for full command output.

설치시 오류가 뜨는데 다른 해결방법이 보이지 않습니다.

**Comment by ummae** [comment]
@choseungwoo1 MacOS이신 것 같네요. pip이 아닌 소스 설치를 하셔야할 것 같습니다. https://github.com/kakao/n2/blob/456329d2fe4e0984e98f26af589a848c424f93bf/INSTALL.rst#installation

**Comment by choseungwoo1** [comment]
감사합니다!
