### ISSUE TITLE
Windows에서의 buffalo 라이브러리 인스톨

### ISSUE THREAD

**Issue by jeayoung114** [kakao/buffalo#28]
안녕하세요 이번 카카오 아레나 Melon Playlist Continuation에 참가하는 대학원생입니다.
buffalo 라이브러리안의 misc폴더에 있는 aux.py파일명때문에 문제가 생깁니다.
aux가 windows에서 예약어라서 생기는 문제인 것 같습니다.

이 때문에 pip install, git clone 어떤 방법을 사용해도 라이브러리가 제대로 설치되지 않습니다.
windows와의 호환을 생각한다면 aux.py의 파일명을 바꾸는게 좋을 것 같습니다.

감사합니다.

**Comment by ummae** [comment]
@jeayoung114 

안녕하세요. 제보 감사합니다.
말씀해주신 부분은 간단히 해결할 수 있는 내용이라 곧, 반영토록 하겠습니다.  (PR 주셔도 .. 😀 )
버팔로가 공식적으로는 윈도우 환경을 지원하고 있지 않습니다. 이 내용외에 다른 문제도 발생할 수 있으니 양해 부탁드릴께요.
