### ISSUE TITLE
Add Algorithm CML

### ISSUE THREAD

**Issue by ita9naiwa** [kakao/buffalo#33]
The model [Collaborative Metric Learning](http://www.cs.cornell.edu/~ylongqi/paper/HsiehYCLBE17.pdf) is very similar to WARP and often outperforms WARP. 
It also works quite well for KNN tasks among items and users. 

It seems not very tricky to implement this model using the existing WARP module in buffalo.

**Comment by ummae** [comment]
@ita9naiwa got it

**Comment by ita9naiwa** [comment]
Cogswell Regularization이라고, Embedding들을 batch 단위로 뽑아서 Covariance를 계산한 뒤에, 이를 줄이는 Regularization이 있는데 이것 때문에 SGD로 CML을 구현하기 어려웠습니당.

적당히 괜찮게 근사하는 방법이 생각나서 간단히 테스트해봤습니다. 깃헙 마크다운은 Latex가 안되서, 간단히 블로그에 [적어봤어요](https://ita9naiwa.github.io/recommender%20systems/2020/10/26/on-cogswell-reg.html)
