### ISSUE TITLE
Multi-GPU Support

### ISSUE THREAD

**Issue by tangzhy** [kakao/buffalo#35]
Do you support training models among multiple gpus? 

I'm asking this because my sparse matrix is quite large like:
- shape: (80M, 60M)
- nnz: 400M

**Comment by ummae** [comment]
@tangzhy It would be helpful to deal large scale data but, we don't have plan to support multiple gpus yet. 
did you try buffalo on the database you mentioned? I wonder how long does it take to finish training.
