### ISSUE TITLE
git clone fail on MS Windows

### ISSUE THREAD

**Issue by skyer9** [kakao/buffalo#4]
```
git clone https://github.com/kakao/buffalo.git c:\gitrepo\buffalo
Cloning into 'c:\gitrepo\buffalo'...
error: unable to create file buffalo/misc/aux.py: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by ummae** [comment]
@skyer9 I don't know how is it related with this repository...

**Comment by skyer9** [comment]
i think filename `aux.py` is problem.

`https://github.com/swcarpentry/DEPRECATED-bc/issues/463`

i think changing filename will fix this problem.

though compiling this repo on MS Windows is very difficult, it is useful just exploring source code without compiling.

**Comment by ummae** [comment]
@skyer9 We don't have plan to support Windows OS in sooner or later(I recommend docker). I will reopen this issue when times come.
