### ISSUE TITLE
h5py==3.7.0 does not support python3.11

### ISSUE THREAD

**Issue by ita9naiwa** [kakao/buffalo#60]

**Comment by ita9naiwa** [comment]
https://github.com/h5py/h5py/issues/2146

latest h5py is not stable in py311.

**Comment by tacaswell** [comment]
h5py 3.7 support py311 and is perfectly stable, however there are not wheels.

If you need built binary packages for h5py + py311 right now I suggest looking at conda-forge.

**Comment by ita9naiwa** [comment]
@tacaswell thanks for letting me know! I'll check

**Comment by ita9naiwa** [comment]
- Checked and ran some tests, buffalo with py311 works well (h5py installed manually)
